### ISSUE TITLE
虾米音乐可以成功解析但是会返回403错误

### ISSUE THREAD

**Issue by cdiscrete** [naoyeye/xiamiRun#2]
虾米可能已经注意到这个问题了。

**Comment by naoyeye** [comment]
http://xiamirun.avosapps.com/run?song=http://www.xiami.com/song/1774205606

hi，你那边访问 demo 也是 403 吗？

**Comment by naoyeye** [comment]
@cdiscrete ping?

**Comment by cdiscrete** [comment]
@naoyeye pong! 现在似乎没问题了。之前一直在忙没上Github，sorry～
